### ISSUE TITLE
As of 0.2.14, all templates give error

### ISSUE THREAD

**Issue by JonathanSerafini** [hw-labs/knife-cloudformation#12]
Since the 0.2.14 gem update, all knife cloudformation validate commands ( create as well as I recall ) will give the error : : FATAL: Invalid template property or properties [sfn_nested_stack].

Reverting back to 0.2.12 removes this error. 

Any information you need for this, just let me know.

**Comment by chrisroberts** [comment]
Hi! Thanks for reporting this. I have applied the update and cut a new release. This should be resolved in 0.2.16. Cheers!
